version: "3"
services:
  gin-blog:
    build:
      context: ./
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: "mysql:5.7"
    container_name: "mysql-blog"
    restart: "always"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "/gin-blog/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gin_blog"